jobs:
  include:
    - stage: ios
      language: objective-c  
      os: osx
      osx_image: xcode11.2 
      cache:
        directories:
        - $HOME/.m2
      env: 
        - NODE_VERSION="8.16.0"
      before_install: 
        - nvm install $NODE_VERSION

      install: 
        - npm install -g appium
        - npm install -g mocha
        - npm install wd 
        - appium --log-level info > appium_log.txt &
        - npm install -g appcelerator titanium alloy
        - ti sdk install latest --no-progress-bars  
        - ti clean
        - ti build -p ios
        - echo "build succeded"

      script:
        - mocha test.js

notifications:
  email:
    - email@mydomain.io